/**
 * ExampleThumbnail — convention-based card thumbnail for an example.
 *
 *   1. Try /examples-thumbs/<id>.webp (real canvas screenshot, generated by
 *      velxio-prod's scripts/capture-example-thumbs.mjs).
 *   2. If that 404s — or if the example has no thumbnail captured yet —
 *      fall back to the existing CircuitPreview component (the SVG mock).
 *
 * WebP only (no PNG fallback): supported by ~97% of browsers in use; the
 * remaining ~3% (very old Safari) gracefully fall back to CircuitPreview
 * via the onError handler.
 *
 * The optional `example.thumbnail` field still wins if explicitly set.
 */

import { useState } from 'react';
import type { CSSProperties } from 'react';
import type { ExampleProject } from '../../data/examples';
import { CircuitPreview } from './CircuitPreview';

interface Props {
  example: ExampleProject;
  width?: number;
  height?: number;
  background?: string;
  style?: CSSProperties;
}

export const ExampleThumbnail = ({
  example,
  width = 300,
  height = 180,
  background = '#0a0a0c',
  style,
}: Props) => {
  const [imgFailed, setImgFailed] = useState(false);

  // Explicit thumbnail wins over convention-based.
  if (example.thumbnail) {
    return (
      <img
        src={example.thumbnail}
        alt={example.title}
        className="example-preview-image"
        style={style}
        loading="lazy"
      />
    );
  }

  if (imgFailed) {
    return (
      <CircuitPreview
        example={example}
        width={width}
        height={height}
        background={background}
        style={style}
      />
    );
  }

  return (
    <img
      src={`/examples-thumbs/${example.id}.webp`}
      alt={example.title}
      className="example-preview-image"
      style={style}
      loading="lazy"
      onError={() => setImgFailed(true)}
    />
  );
};
